### ISSUE TITLE
Deprecation Notice - securepay.php:30

### ISSUE THREAD

**Issue by blairwigley** [hash-bang/PHP-SecurePay#17]
Not sure if this is still being maintained but composer is throwing a depreciation notice, looks like something that could be easily fixed:

Deprecation Notice: Methods with the same name as their class will not be constructors in a future version of PHP; SecurePay has a deprecated constructor in securepay.php:30

**Comment by hash-bang** [comment]
@blairwigley I do believe people are still using the module yes but I'm not actively maintaining it - having moved from PHP to Node myself.

I'll have a look into fixing this up when I can.

**Comment by hash-bang** [comment]
Finally had a chance to sit down now and have a look at this.

Turns out the above issue was in fact already fixed, Composer / Packagist wasn't bringing in the tag because of a typo.

**Comment by Stipo6** [comment]
> Finally had a chance to sit down now and have a look at this.
> 
> Turns out the above issue was in fact already fixed, Composer / Packagist wasn't bringing in the tag because of a typo.

Sorry, I know this was from some time ago, but I recently moved to a new server and now am running PHP 7.3. The secure.php script still runs but with this deprecation notice. I'm using an older version of your solution, not sure what version exactly. 

I thought it prudent to fix this. You say the issue was fixed 'Composer / Packagist wasn't bringing in the tag because of a typo'. Is there something I need to do in the securepay.php script or do I need to download the latest version of the script from github?

Thanks for your time.
